In [1]:
import numpy as np
from math import log

def log2(val):
    return log(val, 2)

# print a matrix for latex
def latex_matrix(A):
    for row in A:
        for ele in row[:-1]:
            print(ele, end=' & ')
        print(row[-1], end=' \\\\\n')

# pretty print for np.array 
# from https://stackoverflow.com/questions/53126305/pretty-printing-numpy-ndarrays-using-unicode-characters/53164538#53164538

def pretty_print(A):
    if A.ndim==1:
        print(A)
    else:
        w = max([len(str(s)) for s in A]) 
        print(u'\u250c' + u'\u2500' * w + u'\u2510') 
        for AA in A:
            print(' ', end='')
            print('[', end='')
            for i, AAA in enumerate(AA[:-1]):
                w1 = max([len(str(s)) for s in A[:, i]])
                print(str(AAA) + ' ' * (w1  - len(str(AAA)) + 1), end='')
            w1 = max([len(str(s)) for s in A[  :, -1]])
            print(str(AA[-1]) + ' ' * (w1 - len(str(AA[-1]))), end='')
            print(']')
        print(u'\u2514'+u'\u2500' * w + u'\u2518')  

def compare(left: set, right: set):
    if len(left) == len(right):
        for i in range(len(left)):
            if left[i] != right[i]:
                return left[i] < right[i]
    return left < right



### Generate $\mathcal{A}_n^2$

> Let $|\cdot|$ denotes cardinality and $\Delta$ denote symmetric different

In [2]:
def Delta(left: set, right: set):
    return left.symmetric_difference(right)

def Cardi(x: set):
    return len(x)

> Let $n=2^m$, $\Omega$ be a set of $m$ element such that $|\alpha_i| \leq |\alpha_{i+1}|$ and $|\alpha_i \Delta \alpha_{i+1}| \leq 2$  
> Let $\alpha_0=\{\varnothing\}$, now genereate $\Omega$

> utils func for checking $|\alpha_i| \leq |\alpha_{i+1}|$ and $|\alpha_i \Delta \alpha_{i+1}| \leq 2$  

In [3]:
def legal(alpha_i: set, alpha_i_1: set):
    return Cardi(alpha_i) <= Cardi(alpha_i_1) and Cardi(Delta(alpha_i, alpha_i_1)) <= 2

def assert_omega(ome, _m, skip=0):
    for i in range(0 + skip, len(ome) - 1):
        if not legal(ome[i], ome[i + 1]):
            print(ome[i], ome[i + 1])
        assert(legal(ome[i], ome[i + 1]))
    assert(len(ome) == 2**_m + 1)

In [4]:
from itertools import chain, combinations

# generate Omega
def insert_one_element(initial_sets: list, super_end: int) -> list:
    res = []
    for initial_set in initial_sets:
        avail_range = list(range(max(initial_set) + 1, super_end + 1))
        if len(avail_range) == 0:
            continue
        if len(res) == 0 and avail_range[0] not in initial_sets[-1]:
            avail_range.reverse()
        elif len(res) != 0 and avail_range[0] not in res[-1]:
            avail_range.reverse()
        for avail_ele in avail_range:
            if avail_ele in initial_set:
                break
            cur_res = initial_set.copy()
            cur_res.add(avail_ele)
            res.append(cur_res)
    
    return res

def create_Omega(_m: int):
    initial_sets = [{i + 1} for i in range(_m)]
    grouped_res = [initial_sets]
    for _ in range(1, _m):
        grouped_res.append(insert_one_element(grouped_res[-1], _m))

    res = [set(), set()]
    for single_res in  grouped_res:
        res.extend(single_res)
    ### the follow code is for verification
    s = list(range(1, _m + 1))
    unoredered = list(chain.from_iterable(combinations(s, r) for r in range(len(s)+1)))
    for ele in unoredered:
        assert(set(ele) in res)
    assert(len(unoredered) == len(res) - 1)
    assert_omega(res, _m)
    ### verification ends
    return res


In [25]:
# test
_test_m = 8
_test_omega = create_Omega(_test_m)
_test_omega

[set(),
 set(),
 {1},
 {2},
 {3},
 {4},
 {5},
 {6},
 {7},
 {8},
 {1, 8},
 {1, 7},
 {1, 6},
 {1, 5},
 {1, 4},
 {1, 3},
 {1, 2},
 {2, 8},
 {2, 7},
 {2, 6},
 {2, 5},
 {2, 4},
 {2, 3},
 {3, 8},
 {3, 7},
 {3, 6},
 {3, 5},
 {3, 4},
 {4, 8},
 {4, 7},
 {4, 6},
 {4, 5},
 {5, 8},
 {5, 7},
 {5, 6},
 {6, 8},
 {6, 7},
 {7, 8},
 {1, 7, 8},
 {1, 6, 7},
 {1, 6, 8},
 {1, 5, 6},
 {1, 5, 7},
 {1, 5, 8},
 {1, 4, 5},
 {1, 4, 6},
 {1, 4, 7},
 {1, 4, 8},
 {1, 3, 4},
 {1, 3, 5},
 {1, 3, 6},
 {1, 3, 7},
 {1, 3, 8},
 {1, 2, 3},
 {1, 2, 4},
 {1, 2, 5},
 {1, 2, 6},
 {1, 2, 7},
 {1, 2, 8},
 {2, 7, 8},
 {2, 6, 7},
 {2, 6, 8},
 {2, 5, 6},
 {2, 5, 7},
 {2, 5, 8},
 {2, 4, 5},
 {2, 4, 6},
 {2, 4, 7},
 {2, 4, 8},
 {2, 3, 4},
 {2, 3, 5},
 {2, 3, 6},
 {2, 3, 7},
 {2, 3, 8},
 {3, 7, 8},
 {3, 6, 7},
 {3, 6, 8},
 {3, 5, 6},
 {3, 5, 7},
 {3, 5, 8},
 {3, 4, 5},
 {3, 4, 6},
 {3, 4, 7},
 {3, 4, 8},
 {4, 7, 8},
 {4, 6, 7},
 {4, 6, 8},
 {4, 5, 6},
 {4, 5, 7},
 {4, 5, 8},
 {5, 7, 8},
 {5, 6, 7},
 {5, 6, 8},
 {6, 7, 8},
 {1, 6, 7, 8

> now that we have $\Omega = [a_{0}, a_{1}, ..., a_{k}]$, we can generate $A=\{\alpha_{ij}\} \in \mathcal{A}_n^2$ by:  
> $$a_{ij} = \begin{cases}
    -1,\;\alpha_j\bigcap(\alpha_{i-1}\bigcup\alpha_i)=\alpha_{i-1}\Delta\alpha_{i}\;and\;|\alpha_{i-1}\Delta\alpha_{i}|=2 \\
    (-1)^{|\alpha_{i-1}\bigcap\alpha_j| + 1},\;\alpha_{j}\bigcap(\alpha_{i-1}\bigcup\alpha_{i})\neq\varnothing\;but\;does\;not\;meet\;the\;condition\;above \\
    1,\;\alpha_j\bigcap(\alpha_{i-1}\bigcup\alpha_i)=\varnothing \\
\end{cases}
$$

In [26]:
def query_element(i: int, j: int, _omega: list) -> int:
    alpha_j = _omega[j + 1]
    alpha_i_1 = _omega[i]
    alpha_i = _omega[i + 1]

    if alpha_j.intersection(alpha_i_1.union(alpha_i)) == Delta(alpha_i_1, alpha_i) \
        and Cardi(Delta(alpha_i_1, alpha_i)) == 2:
        return -1
    elif Cardi(alpha_j.intersection(alpha_i_1.union(alpha_i))) != 0:
        return (-1)**(Cardi(alpha_i_1.intersection(alpha_j)) + 1)
    elif Cardi(alpha_j.intersection(alpha_i_1.union(alpha_i))) == 0:
        return 1
    else:
        raise ValueError("Undefined behavior!")
    
def create_A(_omega, _m):
    A_mat = np.zeros((2**_m, 2**_m))
    for i in range(A_mat.shape[0]):
        for j in range(A_mat.shape[1]):
            A_mat[i, j] = query_element(i, j, _omega)
    return A_mat

In [ ]:
# test
A_mat = create_A(_test_omega, _test_m)
pretty_print(A_mat.astype(int))

### Check $A = LQ$

> Let $Q$ be a $n$ by $n$ matrix given by $q_{ij} = (-1)^{|\alpha_i \bigcap \alpha_j|}$, $Q$ is a symmetric Hadamard matrix, that is $Q^2=QQ^T=nI_n$  
> now we check if $Q$ is a symmetric Hadamard matrix  

In [ ]:
def get_Q(_omega, _n):
    Q_mat = np.zeros((_n, _n))
    for i in range(_n):
        for j in range(_n):
            Q_mat[i, j] = (-1) ** Cardi(_omega[i + 1].intersection(_omega[j + 1]))
    return np.matrix(Q_mat)

Q_mat = get_Q(_test_omega, 2**_test_m)
pretty_print(np.array((Q_mat).astype(int)))
pretty_print(np.array((Q_mat * Q_mat).astype(int)))

> And verify matrix $L = AQ^{-1}$ is a lower triangular matrix

In [ ]:
pretty_print(np.array(np.matrix(A_mat) * np.matrix(Q_mat).I))

### Generate $\mathcal{A}_{n - 1}^1$

> Let $B\in\mathcal{A}_{n - 1}^1$, $\Phi(B)\in\mathcal{A}_{n}^2\;$:
> $$ \Phi(B) = \left(\begin{array}{cc} 
1 & 1_{n-1}\\
-1^T_{n-1} & 2B-J_{n-1}
\end{array}\right)
> $$
>
> notice that the $A_2 \in \mathcal{A}_n^2$ we have has it's first column as:
> $$ A_2 = \Phi(B) = \left(\begin{array}{cc} 
1\\
1^T_{n-1}
\end{array}\right)
> $$
> we need to multiply $\{\alpha_{ij}\}_{2\le i\le n, 2\le j\le n} \in \mathcal{A}_n^2$ with $-1$  
> so we can generate matrix $A_1 \in \mathcal{A}_{n - 1}^1$ with $A_2 = \{\alpha_{ij}\} \in \mathcal{A}_n^2$ using the following relation:    
> $$A_1 = \frac{1}{2}(J_{n-1}-\{\alpha_{ij}\}_{2\le i\le n, 2\le j\le n})$$

In [30]:
def create_A_1_mat(A_2_mat):
    
    A_1_mat = (np.ones(A_2_mat.shape[0] - 1) - A_2_mat[1:, 1:]) * 0.5
    assert((A_1_mat.max() == 1 and A_1_mat.min() == 0) if A_1_mat.shape[0] > 1 else True)
    return A_1_mat


In [ ]:
# test
A_1 = create_A_1_mat(A_mat).astype(int)
pretty_print(A_1)

In [32]:
from scipy.optimize import minimize
from itertools import combinations
from time import time

class CalculateDistanceBetweenPointAndPolytope:
    # Function to calculate the Euclidean distance
    def euclidean_distance(self, x, point):
        return np.linalg.norm(x - point)

    # Function to minimize: distance between the chosen point and the convex combination of the remaining points
    def distance_to_polytope(self, lambda_vals, remaining_points, point):
        convex_combination = np.dot(lambda_vals, remaining_points)
        return self.euclidean_distance(convex_combination, point)

    def calculate_distance(self, matrix, selected_index):
        # Extract the selected point
        selected_point = matrix[:, selected_index]
        
        # Extract the remaining points (excluding the selected one)
        remaining_indices = [i for i in range(matrix.shape[1]) if i != selected_index]
        remaining_points = matrix[:, remaining_indices]
        
        # Initial guess for lambda values (uniformly distributed)
        initial_lambda = np.ones(len(remaining_indices)) / len(remaining_indices)
        
        # Constraints: lambda_i >= 0 and sum(lambda) = 1
        constraints = [{'type': 'eq', 'fun': lambda lambda_vals: np.sum(lambda_vals) - 1},
                    {'type': 'ineq', 'fun': lambda lambda_vals: lambda_vals}]  # lambda_i >= 0
        
        # Minimize the distance to the convex hull (polytope)
        result = minimize(
            self.distance_to_polytope,
            initial_lambda,
            args=(remaining_points.T, selected_point),
            constraints=constraints,
            method='SLSQP'
        )
        
        # The minimum distance
        return result.fun


class CalculateDistanceBetweenHulls:
    # Function to calculate the Euclidean distance between two points
    def euclidean_distance_between_points(self, x, y):
        return np.linalg.norm(x - y)

    # Function to minimize: distance between points from convex hulls of S and T
    def distance_between_hulls(self, lambda_s, lambda_t, points_s, points_t):
        convex_comb_s = np.dot(lambda_s, points_s)
        convex_comb_t = np.dot(lambda_t, points_t)
        return self.euclidean_distance_between_points(convex_comb_s, convex_comb_t)

    def calculate_hull_distance(self, matrix, S_indices, T_indices):
        points_S = matrix[:, S_indices]
        points_T = matrix[:, T_indices]
        
        # Initial guesses for lambda values (uniformly distributed)
        initial_lambda_s = np.ones(len(S_indices)) / len(S_indices)
        initial_lambda_t = np.ones(len(T_indices)) / len(T_indices)
        
        # Constraints: lambda_i >= 0 and sum(lambda) = 1
        constraints_s = [{'type': 'eq', 'fun': lambda lambda_vals: np.sum(lambda_vals[:len(S_indices)]) - 1},
                        {'type': 'ineq', 'fun': lambda lambda_vals: lambda_vals[:len(S_indices)]}]  # lambda_i >= 0
        
        constraints_t = [{'type': 'eq', 'fun': lambda lambda_vals: np.sum(lambda_vals[len(S_indices):]) - 1},
                        {'type': 'ineq', 'fun': lambda lambda_vals: lambda_vals[len(S_indices):]}]  # lambda_i >= 0
        constraints = constraints_s + constraints_t

        # Minimize the distance between the convex hulls of S and T
        result = minimize(
            lambda lambda_vals: self.distance_between_hulls(
                lambda_vals[:len(S_indices)], lambda_vals[len(S_indices):], points_S.T, points_T.T
            ),
            np.concatenate([initial_lambda_s, initial_lambda_t]),
            constraints=constraints,
            method='SLSQP',
            bounds=[(0, 1)] * (len(S_indices) + len(T_indices))
        )
        
        # The minimum distance
        min_distance = result.fun
        # lambda_s_opt = result.x[:len(S_indices)]
        # lambda_t_opt = result.x[len(S_indices):]
        
        return min_distance

    def calculate_all_partitions_and_distances(self, matrix):
        d_plus_1 = matrix.shape[1]  # Total number of points (d+1)
        points = list(range(d_plus_1))   # The indices of points
        
        # Collect all possible partitions (S, T) of the d+1 points
        distances = []
        
        # Iterate over all possible sizes of S
        for s_size in range(2, d_plus_1 // 2 + 1):  # S must contain at least 2 point, and so must T
            if s_size * 2 < d_plus_1:
                for S_indices in combinations(points, s_size):
                    T_indices = [p for p in points if p not in S_indices]
                    start_time = time()
                    distance = self.calculate_hull_distance(matrix, S_indices, T_indices)
                    end_time = time()
                    print(f"Partition S: {S_indices}, Partition T: {tuple(T_indices)}, Distance: {distance}, Time: {end_time - start_time}")
                    distances.append((S_indices, T_indices, distance))
            else: # s_size * 2 == d_plus_1
                combs = list(combinations(points, s_size))
                for S_indices in combs[:len(combs) // 2]:
                    T_indices = [p for p in points if p not in S_indices]
                    start_time = time()
                    distance = self.calculate_hull_distance(matrix, S_indices, T_indices)
                    end_time = time()
                    print(f"Partition S: {S_indices}, Partition T: {tuple(T_indices)}, Distance: {distance}, Time: {end_time - start_time}")
                    distances.append((S_indices, T_indices, distance))

        return distances
    
    def verify_for_m_5(self, matrix):
        d_plus_1 = matrix.shape[1]  # Total number of points (d+1)
        points = list(range(d_plus_1))   # The indices of points
        
        # Collect all possible partitions (S, T) of the d+1 points
        distances = []
        
        # Iterate over all possible sizes of S
        s_size = 16
        half_points = list(range(1, 16))
        for half_s_size in range(0, s_size):
            combs = list(combinations(half_points, half_s_size))
            for comb in combs:
                S_indices = [0] + list(comb)
                for p in range(16, 32):
                    if (31 - p) not in S_indices:
                        S_indices.append(p)
                T_indices = [p for p in points if p not in S_indices]
                start_time = time()
                distance = self.calculate_hull_distance(matrix, S_indices, T_indices)
                end_time = time()
                print(f"Partition S: {S_indices}, Partition T: {tuple(T_indices)}, Distance: {distance}, Time: {end_time - start_time}")
                distances.append((S_indices, T_indices, distance))

        return distances
    
    def verify_for_m_6(self, matrix):
        d_plus_1 = matrix.shape[1]  # Total number of points (d+1)
        points = list(range(d_plus_1))   # The indices of points
        
        S_indices = [0] + list(range(7, 22)) + list(range(42, 57)) + [63]
        T_indices = [p for p in points if p not in S_indices]
        start_time = time()
        distance = self.calculate_hull_distance(matrix, S_indices, T_indices)
        end_time = time()
        print(f"Partition S: {S_indices}, Partition T: {tuple(T_indices)}, Distance: {distance}, Time: {end_time - start_time}")

        return distance
    
    def verify_for_m_7(self, matrix):
        d_plus_1 = matrix.shape[1]  # Total number of points (d+1)
        points = list(range(d_plus_1))   # The indices of points
        
        S_indices = [0] + list(range(8, 29)) + list(range(64, 99)) + list(range(120, 127))
        T_indices = [p for p in points if p not in S_indices]
        start_time = time()
        distance = self.calculate_hull_distance(matrix, S_indices, T_indices)
        end_time = time()
        print(f"Partition S: {S_indices}, Partition T: {tuple(T_indices)}, Distance: {distance}, Time: {end_time - start_time}")

        return distance
    
    def verify_for_m_8(self, matrix):
        d_plus_1 = matrix.shape[1]  # Total number of points (d+1)
        points = list(range(d_plus_1))   # The indices of points
        
        S_indices = [0] + list(range(9, 37)) + list(range(93, 163)) + list(range(219, 247)) + [255]
        T_indices = [p for p in points if p not in S_indices]
        start_time = time()
        distance = self.calculate_hull_distance(matrix, S_indices, T_indices)
        end_time = time()
        print(f"Partition S: {S_indices}, Partition T: {tuple(T_indices)}, Distance: {distance}, Time: {end_time - start_time}")

        return distance

def beautiful_print(results):
    # markdown_output = "| S | T | Distance |\n"
    # markdown_output += "|---|---|----------|\n"

    # for result in results:
    #     s_values = ','.join(map(str, result['S']))  # Convert tuple S to comma-separated string
    #     t_values = ','.join(map(str, result['T']))  # Convert tuple T to comma-separated string
    #     distance_value = result['Distance']
        
    #     # Append row to the markdown table
    #     markdown_output += f"| {s_values} | {t_values} | {distance_value} |\n"
    
    # print(markdown_output)

    # Generate TSV table with three columns, using \t as the separator
    tsv_output = "S\tT\tDistance\n"

    for result in results:
        s_values = ','.join(map(str, result['S']))  # Treat tuple S as a string
        t_values = ','.join(map(str, result['T']))  # Treat tuple T as a string
        distance_value = result['Distance']
        
        # Append row to the TSV table
        tsv_output += f"{s_values}\t{t_values}\t{distance_value}\n"

    with open(f'output_{A_1.shape[0]}.csv', 'w') as csv_file:
        csv_file.write(tsv_output)


In [ ]:
d = A_1.shape[0]
matrix = np.concatenate((np.zeros((d, 1)), A_1), axis=1)
print("Matrix:")
print(matrix)

results = []

for selected_idx in range(matrix.shape[1]):
    start_time = time()
    distance = CalculateDistanceBetweenPointAndPolytope().calculate_distance(matrix, selected_idx)
    end_time = time()
    print(f"Partition S: {(selected_idx)}, Partition T: {tuple(set([_ for _ in range(d + 1)]).difference([selected_idx]))}, Distance: {distance}, Time: {end_time - start_time}")
    results.append({'S': tuple([selected_idx]), 'T': tuple(set([_ for _ in range(d + 1)]).difference([selected_idx])), 'Distance': distance})

distances = CalculateDistanceBetweenHulls().calculate_all_partitions_and_distances(matrix)
for S, T, distance in distances:
    # print(f"Partition S: {S}, Partition T: {tuple(T)}, Distance: {distance}")
    results.append({'S': S, 'T': tuple(T), 'Distance': distance})

beautiful_print(results)

min_distance = min(results, key=lambda x: x['Distance'])
print(f"The minimum distance is {min_distance['Distance']} for partitions S={min_distance['S']} and T={min_distance['T']}")

In [ ]:
d = A_1.shape[0]
matrix = np.concatenate((np.zeros((d, 1)), A_1), axis=1)
print("Matrix:")
print(matrix)

results = []

distances = CalculateDistanceBetweenHulls().verify_for_m_5(matrix)
for S, T, distance in distances:
    results.append({'S': S, 'T': tuple(T), 'Distance': distance})

beautiful_print(results)

min_distance = min(results, key=lambda x: x['Distance'])
print(f"The minimum distance is {min_distance['Distance']} for partitions S={min_distance['S']} and T={min_distance['T']}")

In [15]:
d = A_1.shape[0]
matrix = np.concatenate((np.zeros((d, 1)), A_1), axis=1)
print("Matrix:")
print(matrix)

distance = CalculateDistanceBetweenHulls().verify_for_m_6(matrix)

Matrix:
[[0. 1. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 0.]]
Partition S: [0, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 63], Partition T: (1, 2, 3, 4, 5, 6, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 57, 58, 59, 60, 61, 62), Distance: 0.0007369502575757949, Time: 0.5126605033874512


In [24]:
d = A_1.shape[0]
matrix = np.concatenate((np.zeros((d, 1)), A_1), axis=1)
print("Matrix:")
print(matrix)

distance = CalculateDistanceBetweenHulls().verify_for_m_7(matrix)

Matrix:
[[0. 1. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 1. 0. ... 0. 1. 1.]]
Partition S: [0, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 120, 121, 122, 123, 124, 125, 126], Partition T: (1, 2, 3, 4, 5, 6, 7, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 127), Distance: 0.0006378983066158074, Time: 2.9137449264526367


In [33]:
d = A_1.shape[0]
matrix = np.concatenate((np.zeros((d, 1)), A_1), axis=1)
print("Matrix:")
print(matrix)

distance = CalculateDistanceBetweenHulls().verify_for_m_8(matrix)

Matrix:
[[0. 1. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 0.]]
Partition S: [0, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 255], Partition T: (1, 2, 3, 4, 5, 6, 7, 8, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 8